#!/bin/bash

echo "Configure storm supervisor..."

if [ -z $ZK_NM ]
  then
    ZK_NM=3
fi

if [ -z $NBID ]
  then
    NBID=1
fi

echo "storm.zookeeper.servers:" >> /storm/conf/storm.yaml

until [ $ZK_NM -lt 1 ]; do
  echo "    - \"zookeeper-$ZK_NM\"" >> /storm/conf/storm.yaml
  let ZK_NM-=1
done

echo "nimbus.host: \"nimbus-$NBID\"" >> /storm/conf/storm.yaml

echo "storm.zookeeper.root: \"/storm/$NBID\"" >> /storm/conf/storm.yaml
echo "storm.local.hostname: $STORM_HN" >> /storm/conf/storm.yaml


if [ -z $S_PORT ]
  then
    S_PORT=6704
fi

if [ -z $E_PORT ]
  then
    E_PORT=6700
fi

if [ $S_PORT -lt $E_PORT ]
  then 
    exit 1
fi

if [ $(($S_PORT-$E_PORT)) -gt 9 ]
  then
    echo "WARNING: the port range can't be greater than 10"
    E_PORT=$(($S_PORT-9))
fi

echo "supervisor.slots.ports:" >> /storm/conf/storm.yaml

until [ $S_PORT -lt $E_PORT ]; do
  echo "    - $(($S_PORT+($NBID-1)*10))" >> /storm/conf/storm.yaml
  let S_PORT-=1
done

echo "worker.childopts: \"-Xmx512m\"" >> /storm/conf/storm.yaml

echo "Finish storm configuration."
echo "[Config] The supervisor configuration yaml content:-------------------"
cat /storm/conf/storm.yaml
echo "[Config] -------------------------------------------------------------"

./bin/storm supervisor
